apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
    release: "0-5"
  ports:
    - name: http
      port: 80        # The service port inside the cluster
      targetPort: 80  # The port on the container (inside the pod)
      nodePort: 30080 # The externally accessible port
  type: NodePort
